name: Build Docker

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: 0x-jerry/workflows/.github/workflows/build-docker.yml@main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
