name: GH Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: 0x-jerry/workflows/.github/workflows/gh-pages.yml@main
    permissions:
      contents: write
    with:
      build-cmd: bun run build
      upload-folder: ./dist
