name: GH Pages

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    uses: 0x-jerry/workflows/.github/workflows/gh-pages.yml@main
    permissions:
      contents: write
    with:
      build-cmd: bun run build
      uplaod-folder: ./dist

