name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: 0x-jerry/workflows/.github/workflows/changelog.yml@main
    permissions:
      contents: write
    with:
      build-cmd: bun run build
      uplaod-folder: ./dist

