name: Changelog

on:
  workflow_call:
    inputs: {}
    outputs:
      release-id:
        description: Released ID
        value: ${{ jobs.release.outputs.release-id }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-id: ${{ steps.create-release.outputs.release-id }}
    steps:
      - name: Setup bun
        uses: 0x-jerry/workflows/actions/setup-js@main
        with:
          fetch-all: true

      - name: Release
        id: create-release
        uses: 0x-jerry/workflows/actions/changelog@main
