name: Publish

on:
  workflow_call:
    inputs: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: 0x-jerry/workflows/actions/setup-js@main
        with:
          fetch-all: true

      - name: Install dependencies
        run: bun install

      - name: Publish
        run: bunx npm publish --provenance
